version: 2.1

defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:latest
  working_directory:  /home/circleci

job_environments:
  common_environment: &common_environment
    JOB_ENV_CONSTANT1: Job Environment Constant 1 works fine

jobs:
  echo-vars-job:
    <<: *defaults
    environment:
      <<: *common_environment
    working_directory: /tmp/workspace/src
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: bash /tmp/workspace/src/echo_vars.sh

workflows:
  version: 2.1
  echo-vars-branch:
    jobs:
      - echo-vars-job:
          context: org-global
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  echo-vars-tag:
    jobs:
      - echo-vars-job:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /echo.*/
